AWSTemplateFormatVersion: 2010-09-09
Description: Deploys the VPC for the example Amazon Connect contact center

Resources:
  ExConnectVpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16

  ExSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref ExConnectVpc
      CidrBlock: 10.0.0.0/24

  ExSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref ExConnectVpc
      CidrBlock: 10.0.1.0/24

  ExRouteTable1:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref ExConnectVpc

  ExDynamoDBVPCEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: !Ref ExConnectVpc
      ServiceName: !Sub com.amazonaws.${AWS::Region}.dynamodb
      VpcEndpointType: Gateway
      RouteTableIds:
        - !Ref ExRouteTable1

  ExLambdaVPCEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: !Ref ExConnectVpc
      ServiceName: !Sub com.amazonaws.${AWS::Region}.lambda
      VpcEndpointType: Interface
      SubnetIds:
        - !Ref ExSubnet1
        - !Ref ExSubnet2

  ExSSMVPCEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: !Ref ExConnectVpc
      ServiceName: !Sub com.amazonaws.${AWS::Region}.ssm
      VpcEndpointType: Interface
      SubnetIds:
        - !Ref ExSubnet1
        - !Ref ExSubnet2

  ExS3VPCEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: !Ref ExConnectVpc
      ServiceName: !Sub com.amazonaws.${AWS::Region}.s3
      VpcEndpointType: Interface
      SubnetIds:
        - !Ref ExSubnet1
        - !Ref ExSubnet2

Outputs:
  VpcId:
    Value: !Ref ExConnectVpc
    Export:
      Name: !Sub ${AWS::StackName}-VpcId

  SubnetIds:
    Value:
      !Join [
        ",",
        [!Ref ExSubnet1, !Ref ExSubnet2],
      ]
    Export:
      Name: !Sub ${AWS::StackName}-SubnetIds
