AWSTemplateFormatVersion: '2010-09-09'
Description: PostgreSQL Database on RDS using db.t3.micro instance.

Parameters:
  MasterUsername:
  Description: The database admin account username
  Type: String
  MinLength: 1
  MaxLength: 16
  AllowedPattern: "[a-zA-Z][a-zA-Z0-9]*"
  ConstraintDescription: Must begin with a letter and contain only alphanumeric characters.

  MasterUserPassword:
  Description: The password for the database admin account
  NoEcho: true
  Type: String
  MinLength: 8
  MaxLength: 41
  AllowedPattern: "[a-zA-Z0-9]*"
  ConstraintDescription: Must contain only alphanumeric characters.

  DBSubnetGroupName:
    Description: The DB Subnet Group Name
    Type: String
    Default: your-db-subnet-group

  VPCSecurityGroupIds:
    Description: The VPC security group IDs
    Type: List<AWS::EC2::SecurityGroup::Id>
    Default: sg-12345678

Resources:
  ExRDSInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceClass: db.t3.micro
      Engine: postgres
      EngineVersion: '15'
      AllocatedStorage: '20'
      DBName: MyDatabase
      MasterUsername: !Ref MasterUsername
      MasterUserPassword: !Ref MasterUserPassword
      DBSubnetGroupName: !Ref DBSubnetGroupName
      VPCSecurityGroups: !Ref VPCSecurityGroupIds
      MultiAZ: false
      BackupRetentionPeriod: 0
      PubliclyAccessible: true

Outputs:
  ExRDSInstanceEndpoint:
    Description: The connection endpoint for the database instance
    Value: !GetAtt ExRDSInstance.Endpoint.Address

  ExRDSInstancePort:
    Description: The port of the database instance
    Value: !GetAtt ExRDSInstance.Endpoint.Port
